// Generated by Wrangler

import { KVNamespace } from "@cloudflare/workers-types/experimental";

// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  IVE_SCRIPTS: KVNamespace;
  API_KEY: string;
}
